### PR TITLE
Caesar's Fixgion 

### PR DESCRIPTION
**Pull request by CaesarNVMP**
# **MISUNDERSTANDING. Marcus was only setting me challenges and had no intention to use what I made for him.

I'll be uploading my updated fixes here, starting from TriggerfixV7 at the bottom of the page which has merged the hoover dam and cottonwood cove fix with it. 
And also i'd recommend using RacemenutoolV3 Updated for the race menu addition as the keybinded one could become a combat tabbing issue.**

### CODE REVIEW

**Comment by CaesarNVMP** [comment]
I wasn't sure how to remove the other  outdated trigger esps , oh also i made another esp called unobtainablearmourscavenge , an optional esp that adds some npc only clothing to be scavengeable in the wastes, it also makes the legate's armor playable so it'll show up in the inventory

**Comment by Silentfood** [comment]
Could you move the .esp into the "esps" folder, cheers.

**Comment by CaesarNVMP** [comment]
V3 of Character Creation is the current/updated and final version! tutorial of how the character creation tool works https://www.youtube.com/watch?v=SHlt6YtcNVU&

**Comment by CaesarNVMP** [comment]
Also with CoveAir(Location Saving) And Hoover dam fix , I found a glitched crucified that doesn't show up in singleplayer due to a marking glitch which has been the reason for some vanilla stutters around there which i also fixed while i was at it, he is located on the highest cross on the left as you go towards the cove from the main road, ontop of the rock. But yeah that person shows up correctly now too

**Comment by CaesarNVMP** [comment]
Demonstration video of keybinded Racemenu tool https://www.youtube.com/watch?v=No1idF4ruwE&

**Pull request closed without merging**
